version: "3.9"

services:
  app:
    build:
      context: .
      target: app
    command: uvicorn deepparse.app.app:app --host 0.0.0.0
    tty: true
    ports:
      - "8000:8000"
    profiles:
      - app
    volumes:
      - "/$HOME/.cache/deepparse:/root/.cache/deepparse"