learning_hyperparameters:
  seed: 5
  batch_size: 2048
  epochs_number: 200
  learning_rate: 0.1
  patience: 15
  torch_device: 0
  embedding_size: 300
  padding_value: -32
  num_dataloader_workers: 8
